[package]
name = "halo2wrong"
version = "0.1.0"
authors = ["kilic <kiliconu@itu.edu.tr>"]
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1"
num-traits = "0.2"
# TODO fix when halo2 releases 0.3.1 and halo2wrong uses it
#halo2 = { package = "halo2_proofs", git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v0.3.0" }
halo2 = { package = "halo2_proofs", git = "https://github.com/powdr-labs/halo2", branch = "make-emit-public-v0.3.0" }

[dev-dependencies]
rand = "0.8"
rand_core = { version = "0.6", default-features = false }

[features]
default = []
circuit-params = ["halo2/circuit-params"]
